name: 部署网页到服务器

# 触发条件：推送到 main 分支时自动部署
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装依赖并打包
        run: |
          npm install
          npm run build
          
      # 上传文件到服务器
      - name: 部署到远程服务器
        uses: appleboy/ssh-action@master
        
        with:
          # ========== 必须修改这 4 个参数 ==========
          host: 47.104.134.150      # 服务器 IP
          username: root # 服务器用户名（root 或 ubuntu）
          password: ${{ secrets.SERVER_PASSWORD }} # 改用密码
          timeout: 600s
          # 上传目录：dist 是打包目录 /var/www/website 是服务器网站目录
          script: |
            rsync -avz --delete ./root@${{ secrets.SERVER_HOST }}:/var/www/website/
